Repository AcevedoR/outplant, pull requests merged in 2023-08, with the labels that each got.

#29 add luminescent gene story chain
  chains/luminescent_gene.json
  chains/missing_form.json
  chains/rich_hunters.json
  chains/science_prize.json
  chains/starvation.json
  chains/toxic_rain.json
Labels: content

#31 feat(ui,engine): handle end of game
  Cargo.toml
  src/engine/engine.rs
  src/ui/mod.rs
Labels: engine, UI

#42 deploy to outplant/outplant-dev on itch.io
  .github/workflows/onPush.yml
Labels: itch.io

#46 Effects on transitions + earthquake story
  README.md
  chains/earthquake.json
  chains/schema.json
  chains/science_prize.json
  src/engine/chain_store.rs
  src/engine/engine.rs
  src/engine/event.rs
  src/engine/mod.rs
Labels: engine, content

#47 feat(ui,engine): display events by chain
  src/engine/engine.rs
  src/ui/mod.rs
  style.css
Labels: UI
